fasigner/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from fasigner.settings import *
from app.views import *
from django.conf import settings
from rest_framework import routers
from rest_framework.authtoken import views as authtoken_views
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from schema import schema
#import schema

router=routers.DefaultRouter()
router.register('comment',CommentSet),
router.register('user',UserSet),
router.register('photo',PhotoSet),

urlpatterns = [
    #graphiql=True,
    url(r'^graphql', GraphQLView.as_view(graphiql=True,schema=schema)),
    
    url(r'abc',PhotoSS.as_view()),

    url(r'^api/',include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^img$',Input,name="input-img"),
    url(r'^$',Gallery,name='gallery'),
    url(r'^login',Login,name='login'),
    url(r'^logout',Logout,name='logout'),
    url(r'^auth',auth,name='auth'),
    url(r'^home',home,name='home'),
    url(r'^getcomment/(?P<p_id>.*)/',get_comment,name='getcomment'),
    #url(r'^profile',profile,name='profile'),
    url(r'^accounts',registration,name='registration'),
    url(r'^comment/(?P<p_id>.*)/',ajax_comment,name='comment'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^profile/(?P<pk>.*)/',profile,name='profile'),
    #url(r'^profile/$',UpdateProfile,name='updateprofile'),
    url(r'^updateprofile/$',UpdateProfile,name='updateprofile'),
    url(r'^updatepic/$',UpdateProfilePic,name='updateprofilepic'),
    #url(r'^uploading$',uploading,name="img-uploading"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    about = models.TextField(blank=True)
    birth_day = models.DateField(null=True,blank=True)

    def __str__(self):
        return str(self.user)

"""    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()         """   




class Profile_pic(models.Model):
    profile = models.OneToOneField(Profile,on_delete=models.CASCADE)
    profile_original = models.ImageField(upload_to='photos/profile/original')
    profile_thumbs = models.ImageField(upload_to='photos/profile/thumbs')
    profile_photo = models.ImageField(upload_to='photos/profile/photo')

    def __str__(self):
        return (self.profile.user.username)

    def save(self):
        im = Image.open(self.profile_original)
        output = BytesIO()
        basewidth = 600
        #img = Image.open('somepic.jpg')
        wpercent = (basewidth/float(im.size[0]))
        hsize = int((float(im.size[1])*float(wpercent)))
        im = im.resize((basewidth,hsize), Image.ANTIALIAS)      
        im = im.convert("RGB")
        im.save(output, format='JPEG', quality=70)
        
        self.profile_photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.profile_original.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
        
        weight,height=im.size
        if weight > height:
            r=(weight-height)/2
            imc=im.crop((r,0,height+r,height))
        else:
            r=(height-weight)/2
            imc=im.crop((0,r,weight,height-r))  
        imc = imc.convert("RGB")      
        imc=imc.resize((300,300),Image.ANTIALIAS)
        output = BytesIO()
        imc.save(output, format='JPEG', quality=70)
        output.seek(0)
        self.profile_thumbs = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.profile_original.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
        super(Profile_pic,self).save()


class Photos(models.Model):
    #pic_name=models.CharField(max_length=20)
    original_photo=models.ImageField(upload_to='photos/original')
    thumbs = models.ImageField(upload_to='photos/thumbs/')
    photo = models.ImageField(upload_to='photos/photo')
    created_date=models.DateTimeField(default=datetime.now,null=True)
    #comment=models.TextField()
    upload_by=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return str(self.upload_by)+' : '+str(self.created_date)

    def save(self):
        super(Photos,self).save()
        im = Image.open(self.original_photo)
        output = BytesIO()
        basewidth = 600
        #img = Image.open('somepic.jpg')
        wpercent = (basewidth/float(im.size[0]))
        hsize = int((float(im.size[1])*float(wpercent)))
        im = im.resize((basewidth,hsize), Image.ANTIALIAS)      
        im = im.convert("RGB")
        im.save(output, format='JPEG', quality=70)
        
        self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.original_photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)




        
        weight,height=im.size
        if weight > height:
            r=(weight-height)/2
            imc=im.crop((r,0,height+r,height))
        else:
            r=(height-weight)/2
            imc=im.crop((0,r,weight,height-r))  
        imc = imc.convert("RGB")      
        imc=imc.resize((300,300),Image.ANTIALIAS)
        output = BytesIO()
        imc.save(output, format='JPEG', quality=70)
        output.seek(0)
        self.thumbs = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.original_photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)






        """weight,height=im.size
        output = BytesIO()
        left = (weight - 300)/2
        top = (height - 300)/2
        right = (weight + 300)/2
        bottom = (height + 300)/2

        imc = im.crop((left, top, right, bottom))"""
        
        #new_height = 680
        #new_width  = new_height * width / height
        #new_width=680
        #im = im.resize((new_width, new_height), Image.ANTIALIAS)
        #im = im.resize( (100,100))
        #self.thumbs = output
        #output = BytesIO()
        #imcc=imc.resize((300,300),Image.ANTIALIAS)
        #imcc.save(output, format='JPEG', quality=40,optimize=True)

        #output.seek(0)
        #self.thumbs = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.original_photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
        #super(Photos,self).save()


class Comments(models.Model):
    photo_id = models.ForeignKey(Photos, related_name='comments', on_delete=models.CASCADE,null=True)
    comment_time = models.DateTimeField(default=datetime.now,null=True)
    #upload_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True,related_name='%(class)s_upload_by')
    comment_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    #comment = models.CharField(max_length=100, null=True)
    comment = models.TextField()
    def __str__(self):
        return str(self.photo_id)+' : '+str(self.comment_by)
    


        


        """        weight,height=im.size
        if weight > height:
            r=(weight-height)/2
            imc=im.crop((r,0,height+r,height))
        else:
            r=(height-weight)/2
            imc=im.crop((0,r,weight,height-r))  
        imc = imc.convert("RGB")      
        imc=imc.resize((600,600),Image.ANTIALIAS)
        imc.save(output, format='JPEG', quality=70)
        output.seek(0)
        self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.original_photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
"""

templates/backbone.html
{% load staticfiles %}
<script src="{% static 'backbone/underscore-min.js' %}"></script>
<script src="{% static 'backbone/backbone-min.js' %}"></script>

templates/base.html
{% load staticfiles %}
<html>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
    <meta name="theme-color" content="orange" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'waypoint.js' %}"></script>    
    <script src="{% static 'infinite.js' %}"></script>
<!--    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>-->
    {% include 'backbone.html' %}

    <title>{% block title %}
{% endblock%}</title>

<style>
    .brands{
        padding: 3px;
    }
    .profile_info{
        width: 50%;
        text-align: right;
        display: flex;
        flex-flow: row nowrap;;        
    }
    .brand{
        width: 50%;
    }
    .navdiv{
        display: flex;
        flex-flow: row nowrap;;
    }
    .top_p{
        float: right;
        padding:12px;
        max-width: 90px;
    }

</style>

<body>
    <section class="top">
        <nav class="nav">
            <div class="navdiv">
                <div class="brand">
                    <span class="header_font">
                        <a href="/home"><span style="color:orange">Fasigner</span></a>
                    </span>
                </div>    
                <div class="profile_info" >
                    
                    <span class="top_p"><a href="/home">Home</a></span>
                    <span class="top_p"><a href="/">Upload</a></span>
                    {% if user %}  
                        <span class="top_p"><a href="/profile/{{user.username}}/">{{user.username}}</a></span>
                        <span class="top_p"><a href="/logout/">Logout</a></span>
                    {% else %}
                    <span class="top_p"><a href="/accounts#login">Login</a></span>
                    {% endif %}
                </div>
            </div>
        </nav>
    
        
        <main class=main>
            {% block content %}

            {% endblock %}
        </main>
    </section>
    {% block script %}
    
    {% endblock %}

    {% block backbone %}
    
    {% endblock %}
</html>

templates/base_old.html
{% load staticfiles %}
<html>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
    <meta name="theme-color" content="orange" />
    <title>{% block title %} {% endblock %}</title>
     {% include "js.html" %}
     <link rel="stylesheet" href="{% static 'style.css' %}">

    <head>
            
    </head>
<!--    <center>
            <div class="_heads">
                <h3>Photo Gallery</h3>
                <hr>
            </div>  
        </center>-->

    <body>
    <div class="header">
            <a href="/home"> <h3 class="top_header_text">Fasigner</h3></a>
    </div>

    <div class="home">
            <div class="side">
            <div>
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
       
    {% block script %}
    {% endblock %}
    </body>
</html>

templates/comments.html
<p>kjhgjkhjkhkj</p>
{% for c in p.comments.all %}
<p>{{c.comment}}</p>
{% endfor %}

templates/css.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

templates/home_old.html
{% extends 'base.html' %}

{% block title %}Fasigner{% endblock %}
{% block content %}

<style>

</style>

<div class="container">
    <div class="main">
    {% for p in photos %}
        <section class="img_con">
            <div class="img_header">
                <div class="img_header_title">
                <h4>Uploaded By {{p.upload_by}}</h4>
                <p class="times"> {{p.created_date.date}} at {{ p.created_date.time }}</p>
                </div>
            </div>
            <a href="{{ p.original_photo.url }}">
            <img src="{{ p.photo.url }}" class="m_img">
            </a>
            <div class="img_footer">
                <div class="img_header_title">
                        {% csrf_token %}
                        {{cmt.comment}}
                        <inpsut type="button" value="post" class="post-btn" imgid="{{p.id}}" >
                
                <div class="commentss">
                    {% for c in comments %}
                        {% if p.photo_id == c.id %}
                        <p>{{ c.comment }}</p><br>
                        {% endif %}
                        {% endfor %}
                </div>    
                </div>
            </div>
            
        </section>
    {% endfor %}    
    </div>
</div>
{% endblock %}


{% block script %}
<script type="text/javascript">

    function set_body_height() { // set body height = window height
        $('body').height($(window).height());
      }

    $(document).ready(function() {
        $(window).bind('resize', set_body_height);
        set_body_height();
      });


    $(document).on('click','.post-btn',function(e){
            var cmt=$('#id_comment').val()
            //var btn = $(this).find("input[type=button]:focus")
            
            //var cmt = $(this).find("input[type=text]:focus")
            //console.log(cmt)
            console.log(cmt.prevObject[0])
            //var id = $('.post-btn').attr('imgid')
            
            //console.log(cmt)
            //console.log(id)
    })

</script>
{% endblock %}


<!--
<style>
    .mains{
        margin-left: 25%;
    }

    @media screen and (min-width:300px){
        
        .m_img{
            width: 100%;
        }
        .main{
            margin-left: 0px;
        }
        .img_header{
            height:1.6cm;
            border-radius: 1px;
            border-top: aquamarine;
            background:white;
            padding-top: 2px;
            border:5px;
            width: 100%;
            border-radius: 6px 6px 0px 0px;
        }

        .img_footer{
        height:1.3cm;
        background:white;
        padding-top: 5px;
        border:5px;
        width: 100%;        
        border-radius: 0px 0px 6px 6px;
    }


    }

    
    @media screen and (min-width:720px) {
        .img_con{
            width: 50%;
            margin-left: 40px;
        }

        .m_img{    
            border-radius: 0px 0px 8px 8px;
        }
    }




    h4{
        line-height: 5px;
    }
    .img_header_title{
        margin-left: 10px;
    }

    .time{
        font-size: 12px;
    }
    #_comment{
        margin-top: 5px;
        width: 90%;
        border: none;
        height:2em;
        border-bottom: 2px solid rgb(226, 219, 223);
    }
    #_comment:focus{
        border-color: snow;
        outline: 0;
        border-bottom: 2px solid rgb(226, 219, 223);
        sbox-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px rgba(0, 0, 0, .6);
    }
    #id_comment{
        margin-top: 5px;
        max-width: 90%;
        min-width: 90%;

        border: none;
        max-height: 0.8cm;
        min-height: 0.8cm;

        bosrder-bottom: 2px solid rgb(226, 219, 223);
        
    }

    #id_comment:focus{
        border-color: snow;
        outline: 0;
        bosrder-bottom: 2px solid rgb(226, 219, 223);
        sbox-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px rgba(0, 0, 0, .6);
    }

*/
</style>-->

templates/input.html
{% extends 'base.html' %}
{% include 'css.html' %}
{% include 'js.html' %}

{% block title %}Create Photo{% endblock %}


{% block content %}
<section class="thumb_section">

<style>
    .mids
    {
        width: 250px;
        height: 250px;
        overflow: hidden;
        margin: 10px;
        position: relative;
    }

    imgs {
        
        position:absolute;
        left: -100%;
        right: -100%;
        top: -100%;
        bottom: -100%;
        margin: auto;
        min-height: 100%;
        min-width: 100%;
        border-radius: 8px;
    }  

    .thumbimg{
      border-radius: 9px;
      max-width: 280px;
      padding: 1px;
      
    }
    .thumb_section{
      max-width: 900px;
      margin:0px auto;
    }
    .input-form{
      width: 100%;
    }
    .main{
      display: flex;
      flex-direction: column;
    }
    .thumbs{
      margin:0px auto;
      position: relative;
      width: 100%;
    }
    .mid{
      
      margin-bottom: 10px;
    }
    #show_box{
      float: right;
      max-width: 600px;
      
    }
    .group{
      width: 100%;
      display: flex;
      flex-direction: row;
    }
</style>
  <div id="show_box" style="display:none">
    <img src="" id="show_image">
  </div>

<div class="input-form">
  <form method="POST" action="." enctype="multipart/form-data" id="formUpload">
          {% csrf_token %}
            {{form.as_p}}
          <input type="submit" class="btn btn-primary" value="post">
  </form>
</div>

<div class="thumbs">
    {% for p in photos %}
      <div class="group">
        {% for i in p %}
          <div class="mid">
            <a href="{{ i.original_photo.url }}"><img src="{{ i.thumbs.url}}" class="thumbimg"></a>
          </div>
        {% endfor %}
      </div>
      {% endfor %}      
  </div>
<!--          <div class="mid">
            <a href="{{ i.original_photo.url }}"><img src="{{ i.thumbs.url}}" class="thumbimg"></a>
          </div>
       
                <!--<td><a href="{{i.photo.url}}">{{i.photo.name}}</a></td>-->

</section>
{% endblock %}

{% block script %}
<script type="text/javascript">
   console.log("sdfh")
    $('#id_original_photo').change(function(){
      if(this.files && this.files[0]){
        var reader = new FileReader();
        reader.onload = function(e){
          $('#show_image').attr("src",e.target.result);
          $('#show_box').show()
        }
        reader.readAsDataURL(this.files[0]);
      }
    })
</script>
{% endblock %}


<!--
<script>
    $(function () {
        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
        $("#id_photo").change(function () {
          if (this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
              $("#image").attr("src", e.target.result);
              $("#modalCrop").modal("show");
            }
            reader.readAsDataURL(this.files[0]);
          }
        });
  
        /* SCRIPTS TO HANDLE THE CROPPER BOX */
       
       
        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        console.log($image)
        $("#modalCrop").on("shown.bs.modal", function () {
          $image.cropper({
            viewMode: 1,
            aspectRatio: 1/1,
            strict: false,
            movable : true,
            scalable:true,
            //minCropBoxWidth: 200,
            //minCropBoxHeight: 200,
            ready: function () {
              $image.cropper("setCanvasData", canvasData);
              $image.cropper("setCropBoxData", cropBoxData);
            }
          });
        }).on("hidden.bs.modal", function () {
          cropBoxData = $image.cropper("getCropBoxData");
          canvasData = $image.cropper("getCanvasData");
          $image.cropper("destroy");
        });
  
        $(".js-zoom-in").click(function () {
          $image.cropper("zoom", 0.1);
        });
  
        $(".js-zoom-out").click(function () {
          $image.cropper("zoom", -0.1);
        });



  
        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
          var cropData = $image.cropper("getData");
          $("#id_x").val(cropData["x"]);
          $("#id_y").val(cropData["y"]);
          $("#id_height").val(cropData["height"]);
          $("#id_width").val(cropData["width"]);
          $("#formUpload").submit();
        });
  
      });
  </script>
-->


<!--
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>
-->

templates/js.html
{% load staticfiles %}
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

templates/post.html
{% extends 'base.html' %}

{% block title %}Gallery{% endblock %}
{% block content %}
<div class="row">
    {% if user.username %}
    <h4>Welcome {{ user.username }}</h4>
    {% endif %}
</div>

<!--<style>
    .mid
    {
        width: 500px;
        height: 400px;
        overflow: hidden;
        margin: 10px;
        position: relative;
    }

    img {
        position:absolute;
        left: -300%;
        right: -300%;
        top: -300%;
        bottom: -300%;
        margin: auto;
        min-height: 300%;
        min-width: 300%;
    }    
</style>-->


<a href="/img"><h4>Uploads image</h4></a>
<form method="POST" action="." enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
<table>
<!--        <tr>
        <td>Name</td>
        <td>{{ form.pic_name }}</td>
    </tr>

    <tr>
        <td>Upload img</td>
        <td>{{ form.photo }}</td>
    </tr>
    
    <tr>
        <td>upload_by</td>
        <td>{{ form.upload_by }}</td>
    </tr>        -->
    <tr>
        <td>{{form.as_p}}</td>
    </tr>
    <input type="submit" value="post">

</table>
</form>

<div class="row">
    {% for i in photo %}
        <div class="col-sm-5 col-lg-5 col-md-5">
            <div class="image">
            <img src="{{ i.thumbs.url}}"><!--  width="60%" height=auto>-->
            </div>
        </div>
        {% endfor %}
                <!--<td><a href="{{i.photo.url}}">{{i.photo.name}}</a></td>-->
        </div>  
</div>    
    {% endblock %}
{% block script %}
{% include 'css.html' %}
{% include 'js.html' %}
{% endblock %}